# source "https://berks-api.vialstudios.com"
source "https://supermarket.chef.io"

cookbook "compat_resource"
cookbook "apt"
cookbook "build-essential"
cookbook "curl"
cookbook "java"
cookbook 'elasticsearch', '~> 2.2.0'
cookbook "git"
cookbook "libqt4"
cookbook "libreoffice"
cookbook "libsasl2_dev", path: "kitchen/site-cookbooks/libsasl2_dev"
cookbook "memcached"
cookbook "nodejs"
cookbook "openssl"
cookbook "passenger_nginx", path: "kitchen/site-cookbooks/passenger_nginx"
cookbook "phantomjs"
cookbook "postgresql", git: "git@github.com:phlipper/chef-postgresql.git"
cookbook "python"
cookbook "ruby_dev", path: "kitchen/site-cookbooks/ruby_dev"
cookbook "rvm"
cookbook "yum"
# cookbook 'compat_resource', "12.5.14"
cookbook "xvfb"
cookbook "chrome", git: "https://github.com/dhoer/chef-chrome"
cookbook "firefox"
cookbook 'redisio', '~> 2.3.0'
