driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[firefox_test::default]
      - recipe[firefox_test::version]
      - recipe[firefox_test::x11]
    attributes:

  - name: custom_version
    run_list:
      - recipe[firefox_test::default]
    attributes: { firefox: { version: "28.0+build2-0ubuntu2" } }
    includes:
      - ubuntu-14.04
