# DO NOT ADD ANYTHING ELSE TO THIS MODULE! This is only meant to setup a
# lxd container... notice the host:localhost? This means this will not run
# on the guest, but instead here. If you really need to add something, use
# the "delegate_to: devbox" clause to your command *after* python has been
# added to the guest.

- hosts: localhost
  vars:
    share_host_path: /home/wagoodman/excella
    share_name: devshare
    guest_mount_path: excella
  tasks:
    - name: Create a ubuntu 14.04 container
      lxd_container:
        name: devbox
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/trusty/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      register: container_values

    # This allows for uid mapping to occur (wagoodman=1000 --> ubuntu=1000)
    - name: Make container privileged
      command: "lxc config set devbox security.privileged true"
      # this is not useful for non idempotent steps like this
      changed_when: false
      ignore_errors: true

    - name: Restart container
      command: "lxc restart devbox"
      # this is not useful for non idempotent steps like this
      changed_when: false
      ignore_errors: true

    - debug: msg="Container has ip {{ container_values.addresses.eth0[0] }}"

    #- name: Check for existing share divice
    #  command: bash -c "lxc config show testbox | grep {{ share_name }}"
    #  register: has_shared_dir
    #  ignore_errors: true
    #  changed_when: false

    - name: Add shared directory to container
      command: "lxc config device add devbox {{ share_name }} disk source={{ share_host_path }} path={{ guest_mount_path }}"
      ignore_errors: true
      # when: ...

    - name: Update apt cache
      command: "lxc exec devbox -- apt update"
      # this is not useful for non idempotent steps like this
      changed_when: false

    - name: Add python
      command: "lxc exec devbox -- apt install -y python"
      # this is not useful for non idempotent steps like this
      changed_when: false
